### PR TITLE
Improved time-series support for financial reports.

### LINKED ISSUE #752: Fundamental timeseries is missing data points
# Bug Report

## Describe the bug
The recently added fundamentals time-series to retrieve financial statements is missing (many) data points (e.g. gross profit). The data point types are extracted from an example URL (see #733), but should actually represent the financial data is shown on the Yahoo Finance UI. 

## Minimal Reproduction
`await yahooFinance.fundamentalsTimeSeries('AAPL', { type: 'annual' })`

## Environment
Browser or Node: Node
Node version (if applicable): 
npm version: 10.2.4
Browser version (if applicable):
Library version (e.g. `1.10.1`): 

## Additional Context
In addition `fundamentalsTimeSeries` supports `annual` and `quarterly` but is missing `trailing`.

 @Shadaeiou did an excellent job on the first version. An update is needed on the data point types used.

### PR DESCRIPTION
**Pull request by nocodehummel**
Improved the `fundamentalsTimeSeries` module to retrieve data points for financial reports. This change resolves missing data points in the financial statements. The keys used in the time-series can be maintained with a script. 

BREAKING CHANGE:
- requires option module.
- type string is stripped from the key in the results.

Closes #752.

## Changes
- introduced option `module` ('financials', 'balance-sheet', 'cash-flow')
- set query type with keys specified per module.
- strip option type string from returned data keys.
- introduced script to maintain the keys per module.

## Type
- [ ] New Module
- [ ] Other New Feature
- [ ] Validation Fix
- [X] Other Bugfix
- [X ] Docs
- [ ] Chore/other

## Comments/notes
Awaiting feedback on BREAKING CHANGE and:
1. should it be possible to call `fundamentalsTimeSeries` with custom keys?
2. should *deprecated* historical financial data queries be removed?

### CODE REVIEW

**Comment by nocodehummel** [comment]
Test failed on circleci although all local test passed. I would appreciate help how to resolve this.

**Comment by nocodehummel** [comment]
Moved the time-series keys to a JSON file that can be maintained by a script parsing `har` files.

**Comment by gadicc** [comment]
Thanks, @nocodehummel, for the phenomenal PR!   Great idea to get all the keys from a har file and thanks both for your great implementation and adherence to project styling etc.

This all looks good to me but would love to hear from @Shadaeiou from too.  As for your questions:

1. Agree with the breaking change for `module`.  In theory we should bump a major version but honestly since this has only existed for a week I think we can just push it through :sweat_smile:   Potentially we could (temporarily) insert a default value and give a warning to replicate the previous behaviour, but I don't think it's worth the effort under the circumstances.

2. Re *custom keys*: probably not, as we wouldn't be able to validate the result / provide correct types.  It's a pain to always need to accommodate new keys, but I believe is the right approach and worth the effort.  We could however offer ability for custom keys in conjunction with [`{ validateResult: false }`](https://github.com/gadicc/node-yahoo-finance2/blob/devel/docs/validation.md#skip-validation-completely) if we really wanted.

3. Re *deprecated historical queries*, it's a good question.  I see some data points still exist, so probably better to leave it, however, it would be great for us to log a warning about the situation.  I think that's probably the approach that will be most helpful to people using the library.  It's beyond the scope of this PR though, but if you're keen to do it, it will be very welcome :)

Thanks again for your great work here!  Super appreciated.

Oh and P.S., re `vscode/settings.json`.  Great to specify the `files.eol`, thanks, will def make things easier for Windows contributors.  Re `prettier` settings, I'd prefer to leave everything as the prettier default, and add any necessary exceptions to the `.prettierignore` file.

**Comment by Shadaeiou** [comment]
Awesome work, LGTM! 🎉

**Comment by nocodehummel** [comment]
@gadicc and @Shadaeiou; thanks. Looking forward to a new release.

**Comment by nocodehummel** [comment]
@gadicc for the deprecated historical queries a migration path can be to add three new modules; incomeStatement, balanceSheet and cashflowStatement that map to the `fundamentalTimeseries` to fetch the data. As far as I understand the package schema validation could be used to verify that the results is matching the previous endpoint. The interface looks similar to me and this could potentially be realized without mapping. 

At the same time adding a deprecation warning. Would that make sense as a new PR?

**Comment by nocodehummel** [comment]
Converted back to draft. I noticed on one of my stocks `PHIA.AS` that the module return 5 quarterly income statement, 3 balance sheets and zero cash-flow. Need to investigate.

**Comment by nocodehummel** [comment]
Reviewed the results and the PR is good. The number of reports returned is the same as `devel` without PR. Verified some symbols by comparing with the UI and the number of reports is the same. Added test cases for *AAPL* to check results contain 5 quarterly reports and 4 annual reports with relevant property.

**Comment by gadicc** [comment]
@nocodehummel, thanks again for all your amazing work on this!  Most especially the extra time on testing and checking results, which will no doubt be greatly appreciated by all our users!

All looks great.  I'm going to merge now and this will be in our next release.  There'll be an automated message here once it's published.  I'll respond separately re the migration path.  Thanks so much again, this is great work!

**Pull request merged**
