### PR TITLE
Add `options` module

### PR DESCRIPTION
**Pull request by PythonCreator27**
# New module, `options`
This PR adds a new module :tada: 🥳, `options`! This allows you to query calls and puts (options trading stuff?).

## Changes
- Add new module `options`
- Add tests for the module
- Add docs for the module

## Endpoint Params
`formatted` - formats the response.
`lang` - does nothing???
`region` - does nothing???

## Example usage
```ts
import yahooFinance from 'yahoo-finance2';
yahooFinance.options('AMZN', { formatted: false, region: 'US', lang: 'en-US' }); // default queryOptions
```

## Tests
I have no idea why the tests are failing on CI, they pass locally perfectly.

@gadicc Anything to change/add? Any naming conflicts (that was a slight issue when making the module) that you can spot?

### CODE REVIEW

**Comment by gadicc** [comment]
Awesome, @PythonCreator27, thanks for yet another contribution and your fast work on this.  I'm in the middle of some international travel but will take a look as soon as I'm settled at my destination.  Thanks again.

**Comment by gadicc** [comment]
Hey @PythonCreator27, finally had a chance to look at this.  Once again, this is really great, and I really must commend you on checking all the boxes and making a perfect fit with module style, docs, tests, etc.  Thanks for your continued contributions to the project!

I only have two small comments:

1. `[options.ts:76]` `{ moduleName: "historical" }` :)

1. There are a few additional places where I think it would be nice to coerce to date types, e.g. `expirationDates` array, ` options: [ { expirationDate, calls: [ { expiration, lastTradeDate } ], puts: [ { expiration, lastTradeDate } ]`.  Think that's it, and let me know if you agree.<br>
  It's enough to mark these as `Dates` in the typescript interface (and re-run `yarn schema`), there's interim code in-place that will figure out how to convert everything correctly (if you didn't see it already, `schema-tweak` combined with the `validateAndCoerceTypes: yahooFinanceType` code).

Re **CI failure**, it only occurred to me now that not everyone can see the build failure messages.  I'll see if we can get relevant messages directly into GitHub.  The problem was the schema check... you can check if you're running the same version of `ts-json-schema-generator` and `typescript`, sometimes some of the keys change slightly with different versions, because of a different issue I need to figure out.

Thanks again!  Really great work :raised_hands:

**Comment by gadicc** [comment]
Looks great, @PythonCreator27, thank you!  Ready to merge this when you are.

I changed the schema generation to only include interfaces from the `modules` directory, this excludes the anonymous interface which got a new uuid every time we upgraded `ts-json-schema-generator` (or `typescript`, don't recall).  Unfortunately that created a merge conflict but I'm happy to sort that out my side.

Oh I guess we should also update the docs to reflect the Date types, but since that's a non-code change I'm happy to do that after, up to you.

Thanks again for this contribution!

**Comment by PythonCreator27** [comment]
@gadicc Thanks for resolving the anonymous interface issue! Other than the merge conflict, I think that this should be good! 

Thanks for the amazing module!

**Comment by gadicc** [comment]
Thanks, @PythonCreator27.  Looks great!  Merged and released.

Will reply to your comments on other issues tomorrow.  Have an awesome one :D

**Pull request merged**
