### PR TITLE
fix(quote): make certain properties optional

### PR DESCRIPTION
**Pull request by pudgereyem**
This PR changes so that certain properties for `QuoteBase` is optional. Fixes https://github.com/gadicc/node-yahoo-finance2/issues/42.

## Changes

- Make certain properties optional for `QuoteBase`
- Add a test for symbol `AZT.OL` in `quote` module
- Update schema

## Comments

- The cached response for `AZT.OL` for 10am (`tests/http/quote-AZT.OL-10am.json`) is actually not generated 10am, so should be deleted and re-generated at 10am at some point

### CODE REVIEW

**Comment by gadicc** [comment]
Hey @pudgereyem, thanks for another great PR :)

My only question is if the data in the "10am" file is not actually from 10am and contains roughly the same content as the original file, should we not delete it now before committing?  It's also not actually used / referencing in any tests that I could see?

(I'm also going to make a mental note for myself to rename my own 10am tests to reflect the market state vs time in the filename so it's clear what we're actually testing for with those files and what makes them different).

My general comment as usual is that it's so great that we're figuring out all this stuff now about Yahoo's data and won't have to worry about these kinds of surprises with future use in the library.  So thanks again from me and from all our future users too :)

**Comment by gadicc** [comment]
@pudgereyem going to merge now since I might not be free again today... we'll figure it out about the other file, also #45 might make this stuff a bit easier to reason about too.

**Comment by gadicc** [comment]
Thanks, again!

**Comment by pudgereyem** [comment]
Hey @gadicc , 

> My only question is if the data in the "10am" file is not actually from 10am and contains roughly the same content as the original file, should we not delete it now before committing?

I thought about it, but it would just have been re-generated the next time someone ran `yarn test`. And that would not necessarily be 10am either. That's why I decided to commit the file.

> It's also not actually used / referencing in any tests that I could see?

It is, see https://github.com/gadicc/node-yahoo-finance2/blob/devel/src/modules/quote.spec.ts#L23

> going to merge now since I might not be free again today...

Cheers 🎉 , I'm also going to be fairly offline today - but talk next week!

**Comment by gadicc** [comment]
Ahhhh ok now I'm following :sweat_smile: 

Ok that's perfect, thanks again, @pudgereyem!

**Pull request merged**
