### PR TITLE
Add `sectorKey` and `industryKey` to `assetProfile`

### PR DESCRIPTION
**Pull request by martinnormark**
Fixed validation error in quote summary, caused by new fields in the `assetProfile` module.

## Changes
- Added fields to `quoteSummary-iface.ts` and built schema.
- Added fields to cached JSON validation file.

## Type
- [ ] New Module
- [ ] Other New Feature
- [x] Validation Fix
- [ ] Other Bugfix
- [ ] Docs
- [ ] Chore/other

### CODE REVIEW

**Comment by gadicc** [comment]
Hey @martinnormark, thanks for another very welcome PR.  Apologies for the delay as I've been travelling.  Merging now and this will be in the next release.  Thanks again for your time, efforts and patience.

**Comment by martinnormark** [comment]
Hey @gadicc - no worries, always great to contribute to open source. Hopefully I did the changes in the right way for schema validation.

**Comment by gadicc** [comment]
All looked perfect to me! :100: 

Thanks for your attention to detail :wink:

**Pull request merged**
