### PR TITLE
feat(modules): build (true) esm, (interop) cjs modules; tests/readme

### LINKED ISSUE #126: Convert to ESM module (BREAKING).  Target: end of beta cycle.
**Rationale**
[Sindre Sorhus: Get Ready For ESM](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77)

**Implementation**
[Sindre Sorhus: Pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)

**Sugested timeline**

* Target: before first non-beta release (planned around July)
* When things get quiet on other stuff, perhaps we can release with an `rc` tag.

### PR DESCRIPTION
**Pull request by gadicc**
Closes #126.

Great resource: https://webreflection.medium.com/a-nodejs-dual-module-deep-dive-8f94ff56210e

## Changes

Compile to both ESM and CommonJS modules, supporting both via correct fields in package.json

## Comments/notes

- [X] Initial package.json and tsconfig.json changes
- [X] Change all requires to imports
- [X] Change all refs from './file' to './file.js'
- [X] Tests for importing from both types
- [X] Readme notes

### CODE REVIEW

**Comment by PythonCreator27** [comment]
**Files that need to be changed (for require -> (maybe dynamic) import):**
- [ ] schema-tweak.js
- [ ] yahoo-finance.js
- [ ] env-node.ts (`require()` -> dynamic `import()`)
- [ ] cs2json.spec.ts
- [ ] fetchDevel.js
- [ ] moduleExec.spec.ts
- [ ] validateAndCoerceTypes.ts
- [ ] quoteSummary.spec.ts
- [ ] search.spec.ts
- [ ] marketTimes.js
- [ ] reporter.js
- [ ] setupTests.js
- [ ] summary-reporter.js
- [ ] updateJson.js

**Comment by gadicc** [comment]
Thanks, @PythonCreator27, you're so fast :sweat_smile: 

Will be a few days until I have time to work on this again but that's a great help.

**Comment by gadicc** [comment]
Merged to devel.  Hopefully we'll still have some time before next release and can see if any issues crop up.  Can revert if necessary.  We have sanity tests to load in both ways, clear README instructions, and I'm using this in an "interop" (babel) project that uses "es-style" CJS modules and all works as expected.

**Comment by PythonCreator27** [comment]
@gadicc Tests no longer work on windows or WSL. I am trying some hacks and reverting some things to make it work. I think that some parts of this PR will have to be reverted, like the tests. After reverting the .js addition and the changes to the jest config, I still failed to get tests running. `node_modules/.bin/jest` doesn't work on windows, see facebook/jest#3750. Next, after fixing that, the tests fail saying that "the test environment has already been torn down", pointing at `await import('./lib/fetchDevel.js')`.

**Comment by PythonCreator27** [comment]
@gadicc Tests no longer work on windows or WSL. I am trying some hacks and reverting some things to make it work. I think that some parts of this PR will have to be reverted, like the tests. After reverting the .js addition and the changes to the jest config, I still failed to get tests running. `node_modules/.bin/jest` doesn't work on windows, see facebook/jest#3750. Next, after fixing that, the tests fail saying that "the test environment has already been torn down", pointing at `await import('./lib/fetchDevel.js')`.

Jest ESM support is currently poor, I think that this PR should be held off until ESM support works properly in jest, or at least until tests work on all platforms.
Also see #167.

**Pull request merged**
