### PR TITLE
fix(validation): updated upgradeDowngradeHistory Grades

### PR DESCRIPTION
**Pull request by z3nful**
## Changes
- Added missing possible entries
- in very rare cases, currentPrice is not returned in FinancialData, switched it to optional

## Type
- [ ] New Module
- [ ] Other New Feature
- [X] Validation Fix
- [ ] Other Bugfix
- [ ] Docs
- [ ] Chore/other

### CODE REVIEW

**Comment by gadicc** [comment]
Awesome!  Thanks, @z3nful, for another one of these :pray: 

Noted the "Not a typo, how it was returned from API" 😂  Yahoo :man_shrugging: 

I'm assuming the `BUy` and `HOld` is the same story, I would just duplicate the same comment again to make this clear... and so that no one accidentally "fixes" this in the future on our side.

Otherwise looks great and thanks as usual!

**Comment by z3nful** [comment]
Np : )

I just added the note to the other 2 as well. It seems like 'SEll' could logically also be returned at some point, but I checked that module against 10k different stocks and its possible that these typos are just years old and have had some type of validation built in since then on Yahoos side.

**Comment by gadicc** [comment]
Awesome, thanks so much! :pray: 

Yeah a big part of the validation is basically crowdsourcing community knowledge around weird API responses and this is certainly one of them!  And the typescript integration makes this so great... the compiler will now warn people if they accidentally *correctly* spell these things and help them spell it in a way will keep their code working as expected!

**Pull request merged**
