### PR TITLE
Update quoteCombine.md

### PR DESCRIPTION
**Pull request by glaucoheitor**
Fixing small typos. :)

Closes # .

## Changes
- 
- 
- 

## Type
- [ ] New Module
- [ ] Other New Feature
- [ ] Validation Fix
- [ ] Other Bugfix
- [X] Docs
- [ ] Chore/other

## Comments/notes
Just fixing small typos. :)

### CODE REVIEW

**Review by PythonCreator27 — COMMENTED** [review]
This (`{ fields }`) isn't a typo at all. This is a JS shorthand.

**Comment by glaucoheitor** [comment]
I tried on my code and it didn't work, so I assumed it was a typo. i
apologise.

**Comment by gadicc** [comment]
Hey @glaucoheitor, thanks for your contribution!  And thanks @PythonCreator27 for reviewing.

Would you like to update this to just correct the `result` typo?

The JS shorthand that PythonCreator27 mentioned has been around [since ES2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#new_notations_in_ecmascript_2015).  It's super handy.  You should look at upgrading your environment or enabling later presets, as you're probably missing out on a lot of new useful features in JavaScript from the last 6 years.

Thanks again for contributing.

**Comment by glaucoheitor** [comment]
Sorry for that huge time to reply, I just got back to my project. I learned a lot about new features and now I feel a little stupid about my previous commit. I appreciate your patience @gadicc.

I submit a new commit with just the typo correction.

**Comment by gadicc** [comment]
Ah that's great, thanks so much.  Glad you're enjoying all JavaScript's fun new features 😁

**Pull request merged**
