### PR TITLE
Improve quoteSummary documentation

### LINKED ISSUE #260: Docs: Add missing responses of submodules in quoteSummary documentation
# Docs Improvment

## Suggested Improvement
Complete the example responses of the quoteSummary submodules.

## Reason For Suggestion
Currently some submodules of the quoteSummary module dont have any example responses. This makes it hard to work with these submodules, since you dont know the reponse structure of the submodule. See the following image, which represents the current state of the `devel` branch.
image

I already started documenting some submodules in a fork, which can be seen here: [quoteSummary.md](https://github.com/RoXioTD/node-yahoo-finance2/blob/devel/docs/modules/quoteSummary.md)

If you are agreeing with me on this Issue I would be pleased to document more submodules and create a PR.

TODO
- [x] cashflowStatementHistoryQuarterly
- [x] fundOwnership
- [x] fundPerformance
- [x] fundProfile
- [x] incomeStatementHistory
- [x] incomeStatementHistoryQuarterly
- [x] indexTrend
- [x] industryTrend
- [x] insiderHolders
- [x] insiderTransactions
- [x] institutionOwnership
- [x] majorDirectHolders
- [x] majorHoldersBreakdown
- [x] netSharePurchaseActivity
- [x] quoteType
- [x] recommendationTrend
- [x] sectorTrend

### PR DESCRIPTION
**Pull request by RoXioTD**
Closes #260 .

## Changes
- improve the `quoteSummary.md` documentation

## Type
- [ ] New Module
- [ ] Other New Feature
- [ ] Validation Fix
- [ ] Other Bugfix
- [X] Docs
- [ ] Chore/other

## Comments/notes
Only the `secFilings` submodule is missing documentation. However this is currently not possible since it looks like yahoo changed the API and now the submodule always throws a validation error. The progress of this issue can be tracked here #261

### CODE REVIEW

**Comment by gadicc** [comment]
Hey @RoXioTD, this is a really big help, thanks so much!

Reading through it, it made me realize we have a few bugs, with some fields that should return dates are returning numbers instead.  I started tracking them in #263.

Are you still working on this?

I only have one small nitpick, just for the sake of consistency...  we've been showing date fields like this in the docs until now:

```js
  {
    maxAge: 1,
    filerName: 'TAYLOR RYAN D.',
    startDate: 2020-11-17T00:00:00.000Z,
  }
```

i.e. without quotes, to show that it's not a string but a date.  Other than that I'll be very happy to merge this.

**Comment by RoXioTD** [comment]
@gadicc Yeah you are right with the date field format. I will adjust the date fields to have the same format like the rest.

**Comment by RoXioTD** [comment]
@gadicc Dates have now the correct format.

**Comment by gadicc** [comment]
Amazing!  Thanks so much for this.

**Pull request merged**
