### PR TITLE
feat(quote): allow quote of specific options

### PR DESCRIPTION
**Pull request by Sciguymjm**
## Changes
- quote: allow quote of specific options

## Type: Other New Feature

### CODE REVIEW

**Review by PythonCreator27 — CHANGES_REQUESTED** [review]
Just a nit pick: Could you run prettier? Otherwise, this is a pretty good PR. Tests are passing, with 100% coverage! Maybe you want to add some docs about this, and maybe an example, see PRs like #152. This one will be a bit different, but adding some docs would surely help people find this sort of unknown feature.

**Comment by Sciguymjm** [comment]
I ran prettier, but maybe not with the right options? The first version of this PR failed with style checks and this one was okay.

I can add a doc. It's the same syntax as a regular quote, just different results.

**Comment by gadicc** [comment]
Hey @Sciguymjm, thanks for this awesome first contribution! :tada: 

It is very much appreciated when people take the time to learn the coding style and best practices of a project before contributing, so special thanks for new interface, tests, etc.

Great to have working options support now! :pray:

**Pull request merged**
