### PR TITLE
feat(module): Add new fundamentals time series module

### LINKED ISSUE #745: New module request: timeseries
# Feature Request

## Wanted Module: timeseries

This is particular import because the "financials" section of `quoteSummary` no longer includes all this data, as tracked in https://github.com/gadicc/node-yahoo-finance2/issues/733.

## Endpoint

`https://query2.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/AAPL?lang=en-GB&region=GB&symbol=AAPL&padTimeSeries=true&type=annualEbitda%2CtrailingEbitda%2CannualDilutedAverageShares%2CtrailingDilutedAverageShares%2CannualBasicAverageShares%2CtrailingBasicAverageShares%2CannualDilutedEPS%2CtrailingDilutedEPS%2CannualBasicEPS%2CtrailingBasicEPS%2CannualNetIncomeCommonStockholders%2CtrailingNetIncomeCommonStockholders%2CannualNetIncome%2CtrailingNetIncome%2CannualNetIncomeContinuousOperations%2CtrailingNetIncomeContinuousOperations%2CannualTaxProvision%2CtrailingTaxProvision%2CannualPretaxIncome%2CtrailingPretaxIncome%2CannualOtherIncomeExpense%2CtrailingOtherIncomeExpense%2CannualInterestExpense%2CtrailingInterestExpense%2CannualOperatingIncome%2CtrailingOperatingIncome%2CannualOperatingExpense%2CtrailingOperatingExpense%2CannualSellingGeneralAndAdministration%2CtrailingSellingGeneralAndAdministration%2CannualResearchAndDevelopment%2CtrailingResearchAndDevelopment%2CannualGrossProfit%2CtrailingGrossProfit%2CannualCostOfRevenue%2CtrailingCostOfRevenue%2CannualTotalRevenue%2CtrailingTotalRevenue&merge=false&period1=493590046&period2=1709803615&corsDomain=uk.finance.yahoo.com`

Sample output is at https://github.com/gadicc/node-yahoo-finance2/issues/733#issuecomment-1983185092.

### Query Params
| Name | Type | Required |
| ---- | ---- | -------- |
|      |      |          |

TODO

## Potential Example Usage
This module *could* be used in the following way:
```ts
// TODO
```

### PR DESCRIPTION
**Pull request by Shadaeiou**
Closes #745 

## Changes
- Added module
- Added tests
- Added docs
- Updated schema
- Updated common

## Type
- [ x] New Module
- [ ] Other New Feature
- [ ] Validation Fix
- [ ] Other Bugfix
- [ ] Docs
- [ ] Chore/other

## Comments/notes

### CODE REVIEW

**Comment by gadicc** [comment]
Wow :open_mouth:   You, Sir, are a legend!  :bow: 

1. It's your first contribution to the project
2. It's an entirely new module
3. It's a perfect submission in terms of style, docs, tests, etc.

Thanks so much!  This is great!  And so well timed.  :pray: :pray:

**Comment by gadicc** [comment]
This will be in the next release, and there'll be an automated message here when that happens.

Thanks once again.  How was your first contribution?  Is there anything we can make clearer anywhere?

**Comment by Shadaeiou** [comment]
> This will be in the next release, and there'll be an automated message here when that happens.
> 
> Thanks once again. How was your first contribution? Is there anything we can make clearer anywhere?

Hey, no problems! I've been using this library for a long time so it was nice to dig in and see how it works! I figured what I've written is probably a good start and can be iterated on, I just really wanted the data and was sad when I saw that they must have changed the API!

The actual code was easy to write because I had so many good examples to reference. As for the actual contributing documentation, well considering that I've used little very little Typescript and very little yarn, it was actually very easy! I missed formatting and coverage at first and that was definitely user error, which was eventually caught by CI and I was able to easily correct.

Thanks for all your hard work and kudos for such a well written library! I'll definitely keep my eyes open for more ways I can contribute!

**Pull request merged**
